---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: immich-library
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /srv/immich/library
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: immich-database
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/immich/database
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
