---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/component: gitea-checkpoint
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
  name: gitea-checkpoint
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: gitea-checkpoint
            app.kubernetes.io/instance: gitea
            app.kubernetes.io/name: gitea
        spec:
          containers:
            - args:
                - /data/db.sqlite3
                - PRAGMA wal_checkpoint(TRUNCATE);
              image: docker.io/alpine/sqlite:3.51.2
              imagePullPolicy: IfNotPresent
              name: checkpoint
              resources: {}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsNonRoot: true
              volumeMounts:
                - mountPath: /data
                  name: data
          imagePullSecrets:
            - name: docker-hub
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          serviceAccountName: gitea
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: gitea-data
      ttlSecondsAfterFinished: 21600
  schedule: 0 */6 * * *
  timeZone: Etc/UTC
