---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: flux-system
  namespace: flux-system
spec:
  artifacts:
    - copy:
        - from: "@flux-system/apps/base/**"
          to: "@artifact/base/"
        - from: "@flux-system/apps/tombstone/**"
          to: "@artifact/tombstone/"
      name: apps
      originRevision: "@flux-system"
    - copy:
        - from: "@flux-system/infrastructure/configs/**"
          to: "@artifact/"
      name: infra-configs
      originRevision: "@flux-system"
    - copy:
        - from: "@flux-system/infrastructure/controllers/**"
          to: "@artifact/"
      name: infra-controllers
      originRevision: "@flux-system"
  sources:
    - alias: flux-system
      kind: GitRepository
      name: flux-system
