---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  patches:
    - patch: |-
        - op: replace
          path: /spec/addresses
          value:
            - 192.168.1.2/32
            - 2a0b:9401:8b:1:3e07:54ff:fe5c:dd07/128
      target:
        kind: IPAddressPool
        name: default
        # - patch: |-
        #     - op: replace
        #       path: /spec/routes/0/match
        #       value: Host(`traefik.home.arpa`)
        #   target:
        #     kind: IngressRoute
        #     name: traefik-dashboard
        #     namespace: traefik
  path: ./
  prune: true
  sourceRef:
    kind: ExternalArtifact
    name: infra-configs
  retryInterval: 2m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  path: ./
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: ExternalArtifact
    name: infra-controllers
  timeout: 5m
