apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:Krc9ruGAf2vww8w=,iv:rJkFXgMV5PPdYvtN6KpUofDHtllWcwv1xqWjC692ewE=,tag:Lc3xlfuHSSq5oaBxz6M4MQ==,type:str]
      type: ENC[AES256_GCM,data:on9YOWWJ,iv:NPS+NDQgmEo4cUbt90JE1WjkSE+0lWE/QBb2PFXqyzE=,tag:efJLI6qcI53kwigd+QJ47A==,type:str]
      stringData:
        ADMIN_TOKEN: ENC[AES256_GCM,data:kmJZErNFN83ZFjZXbe+HfpqALpS6M2wLWA9FbDKWsYDpz9/ns7EcJLKZG0GgRwgxTHlniboYD92jENLwZmyiWYU5e14oT8NM2OKouE/BO34MVY8/d6IFO/pZkJyex0lXqL7BhWpKKTrfoYcydklqWP+ffjKZZg==,iv:nAnEmTKGvg8WN0MglSdcZc7/8d7lVLX3zLmSVASfA78=,tag:ZEMXqwcdBY25xp3Xs6quKg==,type:str]
        PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:s64qjofrDg4bcLz3du4z2dDuhD5r78hjx2ShFt98j96q+3Mq,iv:fgO7uRax2vKmH6ei9uBo5pcIEmVekbp7gxrh+W0CvXg=,tag:z+kjFPongP4Stu5WGHPS5A==,type:str]
        PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:FeF86Nf6W297uEXibFDyVRTrUro=,iv:vhFRhgjvctuQGuKNFMl+T64nFwmiFfoUerb/E27bttw=,tag:rLsag6UBpyjvrjfKeabZLw==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeFhrZFQ5UGhKWTc3dURB
        Mnc1WVBocko4bHErNk1FSlZUdmtIUEVHSzNvCkN0VUR4MXc2Ym5QNVpXZlJnSFA1
        UlZONUFRMExDM1RPQlFzZ0xnRTZnRlEKLS0tIHlWV1FXSFVDcVNEVER3WThXckVM
        U1dPeFNSOUlXOEw4eVRBNHRqQ1cwVjgKy99XsZuVgqJlTI6uRSYQ3oxkBQ/SKArN
        sG7VU8QsFcJpPZ7k9O5OJNaMujAvFgSPHkZESRbu8pAjTkpAOvbAUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T23:49:28Z"
  mac: ENC[AES256_GCM,data:f42glb4kY6guN+YjTiRL6BIXKb97TEAABoZqTBx18W7j9SI9wcMDnw0FtyYiyXMvZzGfpkQ7bhZ8L/a98GC5t70r/yW1Pnni8dkma1hMlcqM63bITV3vgiphFLsCK4r6PqgosmnDlOkERyzvg2MUw7jg0I4OnAE8oEr79rShyd0=,iv:hck/3jJP6WAAKGZpu3kxtL0F/91Lyem+dyC+OfHdHF4=,tag:/0P1yT1RB1PbCb0vF699FA==,type:str]
  encrypted_suffix: Templates
  version: 3.11.0
