apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig
  namespace: vaultwarden
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:H5Ak5sSeovm8TEvBxxFJrvrA8PHwD+K6qjRWXb0rEqkItyoXpb/eEFva6sYIb3QjkozLeV93EFspOxOQXIYh9o0Gq22lBqk8rpVH2KDs2V4f7v3X3jAVLBwdR2FsqOvIPWdteD4dAgcbudB4fy7zf+kxpSivqtW7kKwhcz7+BqClt06oMRacQoFcB9+weQDtkxjzwvc=,iv:1poFpgNonVwndh13COlaqa7kgFgjELJZUviWLpFTWkc=,tag:pp/NddrqX1K3o4oEj0d8bg==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdjZZS0NBMkFCYnc3L0FF
        TS9oc21GYm4wV3Q1STAvZDVSQjNNSGladzJnClF0b2x1Y3BLdHlpUFV1akRjSjhX
        OWJHaW9URTU5UlZlUzlpbkF0VXRYa3MKLS0tIGxkd0tCMWZtdjg2djlVdlB2SE5H
        eUtlNkZOelJUb01zdXQxUVJJbWN4UlkKoGmr0u7bJ2jlWpR7szhKSg/BtNL01XTY
        +wSyEhqePnge3OB3+gwXHJ17ha647ChBwbpByK54Sya2BEe5LUSZHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T18:15:07Z"
  mac: ENC[AES256_GCM,data:FQsKzHXUJmOQtAJYIrtSMdXHRWNn+iXctTx7xCUQJSQ7YYQyVwmNnk3QnWDUGzmgQXEgaHoGjRXpb69zVIn0zgG91U1/7sSvpqPw+3tVfC5CJniLrN5PNOp37u1/w8GRnCaf+2joxoyksxhzNpgcsgqOehCvrqRk2NduBz2Z2bE=,iv:jiSF9a7tItLhp8NtPq3YizN6P8Yp9ahFYUI2kjryh7g=,tag:NiEas9iJcInn9k+cResUZA==,type:str]
  version: 3.13.3
