apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig
  namespace: rsshub
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:WQ9u4H9sOnLkSoXisbEPKKqoyA49b/5ZXXBRJlhACcYor7VljbiZPKT1Zzh6lr1JYWO3qhb1xZK0EsrN+1Q0kG8mvgq/kA9RRldBpGJ/KIWjqZdJP7bah1sj7T0ab2QdGwg2MQh5Xo0nOS1+YmSshKLkn5LgN6QVEfn0NUbKOQFfpSQr+f1XjpMQyWff+14S9vyQi88=,iv:9FHZV0/FR1X6Kt8FMTruDdbKrO7nfBBRXTEbbYopGUk=,tag:JZqdv6JluaPr36+gk05ZKQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdjZZS0NBMkFCYnc3L0FF
        TS9oc21GYm4wV3Q1STAvZDVSQjNNSGladzJnClF0b2x1Y3BLdHlpUFV1akRjSjhX
        OWJHaW9URTU5UlZlUzlpbkF0VXRYa3MKLS0tIGxkd0tCMWZtdjg2djlVdlB2SE5H
        eUtlNkZOelJUb01zdXQxUVJJbWN4UlkKoGmr0u7bJ2jlWpR7szhKSg/BtNL01XTY
        +wSyEhqePnge3OB3+gwXHJ17ha647ChBwbpByK54Sya2BEe5LUSZHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T18:14:55Z"
  mac: ENC[AES256_GCM,data:eBOqamUGDvrP+rwOP9E3DNXF3/CBmkBnRsVkoNy5CVLOdLP22+cxQn2VZCfD0IOznM/wFCrox44ynoX4gK3N0sTPHZFDhzaTORhpulw3cZSOuiQc8JdFVFKiMZ2ygDmL0g53fXBvgYxoNoTKVnNLnzbpw+YdxQGqraYOR8Ja+Dw=,iv:dnBZOV3okb5KjeqU3qMg0eRbxBtwBYgkFPunberVluo=,tag:b7pCHgzHAxSAMV/tLCG/JQ==,type:str]
  version: 3.13.3
