apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig
  namespace: mitmproxy
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:lJD33MYy/oyBI4AYwgrdOvPbOj2ThnajANStisMlM7T2o5L2j7qa1CuS7BOvYnxUozcDcXMIwbB15P/Ghjo8SptuBJwYkyRxY1DoOM8jptDFVYKaxzTx9/5Cdhy5YPVw3zmmlPRGePfV0ONgbXa1eA1Qk4eezoBtW3uqAtAhzRAasGMqcgKmlE4tVk56z5vTtJDEhHE=,iv:o50bNqC9iKhscD4Ao+rd5tOPKsJTmqVLLvD90vgMpek=,tag:6PAO5TgrNLU+RzYXi5o8AQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMUtsRGYzUVUxalJKaWVJ
        UjdKZUYraTlZVi9CcDV1ZDltOUo2bzZwNlM4CmNlOEpsTzFDVHY2aDlMMkptTVow
        M1paS09TMmh4anBsV1NSN0VnSkl6d0UKLS0tIGRETUlIcXpCZEtucitJbVorTjZG
        d2tFN0wwU2o1T3pTUmNQT2R6S01WTEEK9nULiCwgcN5H0HIRPZ+Ky7rx4Ntg2rqH
        6KMn8vo3/6/JhHoX+oGVuuCH/J2ro+MyCYXiXG3+WhauVt2jmocm8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T18:14:40Z"
  mac: ENC[AES256_GCM,data:En6tJMaTmgYFgbIEWXKKB+Yvh6U40f4C8u2w9Fs5naC3r1MRGSsbwfHMRoejQTMocjcHYzfbDwKQxBmLC2InI2RKIlcxVJQSH2aYuWHuF6MUAEncO1E7MG9e9boz0vQC353rwlffPzAELgbUCUlSPzT4mJE/xqN47Kh72/6+f8k=,iv:BgF16EkFYyRsA+7GlGbIzhDWc64LleymOtjYtdBd/y0=,tag:sEdZ1AaOujMtkJ6H5hWAaw==,type:str]
  version: 3.13.3
