---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: 0.15.3
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 1h
  upgrade:
    crds: CreateReplace
  values:
    networkpolicies:
      enabled: true
    speaker:
      enabled: false
