apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig
  namespace: miniflux
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:SboNvEVTrIlQRCQ+l9UWwbR68fAlgdjMBkbDyjiBAgx549mv8U6CMg5EBd3PY66Mi1J7ph4CYUj685oBgte/C6MKUQS4PK6CVscXHRK3XM7eS4NWPxuxfjp0+ICqG8mkcfTJHSIyVuUo9kPK7Kval2mMujpXNtZFQRhOPOB0E50YQJj7+m5BcwDORtDqH1srYG4vAEQ=,iv:PgoucnIHlYftMBvEIkwKqjY4Xqosz+Yk8slt5U0ZmCo=,tag:2QSLrwSm8O2WK/o4pMmn7g==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdjZZS0NBMkFCYnc3L0FF
        TS9oc21GYm4wV3Q1STAvZDVSQjNNSGladzJnClF0b2x1Y3BLdHlpUFV1akRjSjhX
        OWJHaW9URTU5UlZlUzlpbkF0VXRYa3MKLS0tIGxkd0tCMWZtdjg2djlVdlB2SE5H
        eUtlNkZOelJUb01zdXQxUVJJbWN4UlkKoGmr0u7bJ2jlWpR7szhKSg/BtNL01XTY
        +wSyEhqePnge3OB3+gwXHJ17ha647ChBwbpByK54Sya2BEe5LUSZHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T18:14:31Z"
  mac: ENC[AES256_GCM,data:uN+EXowL7CdWyQnvuBEkkhQk0rTYTHJLtDx1VbCK87DwCOF+9zx3kBEFlPCCM7kDhwg3WdIUlSgO07WhVf4ORnFFQPqSVr8mVUB3QbYvGTKxnC0Cb3b26h/UcG4Pwpd50SsOnqwvXg2Gvw91rypVF1syB/itnwwB5g2lDz1S0H0=,iv:hJoD6Lavjyi+J7qrexRJUwG8a6isiEioMgIheeT0gGg=,tag:wDI60Gb2ONswpuXZGkweYw==,type:str]
  version: 3.13.3
