---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: instagram
spec:
  dnsNames:
    - instagram.com
    - www.instagram.com
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  renewBefore: 8h
  secretName: instagram-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: medium
spec:
  dnsNames:
    - medium.com
    - www.medium.com
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  renewBefore: 8h
  secretName: medium-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skimresources
spec:
  dnsNames:
    - go.skimresources.com
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  renewBefore: 8h
  secretName: skimresources-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: twitter
spec:
  dnsNames:
    - twitter.com
    - www.twitter.com
    - www.x.com
    - x.com
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  renewBefore: 8h
  secretName: twitter-tls
