---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: sops
spec:
  interval: 1h
  chart:
    spec:
      chart: sops-secrets-operator
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: sops-secrets-operator
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    extraEnv:
      - name: SOPS_AGE_KEY_FILE
        value: /etc/sops-age-key-file/key
    secretsAsFiles:
      - mountPath: /etc/sops-age-key-file
        name: sops-age-key-file
        secretName: sops-age-key-file
    securityContext:
      container:
        enabled: true
      enabled: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: sops-secrets-operator
            patch: |
              - op: add
                path: /metadata/annotations/secret.reloader.stakater.com~1reload
                value: sops-age-key-file
