---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nullclaw-workspace
  namespace: nullclaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
