apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: gitea-admin
  namespace: gitea
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:36KUqWKCzuZTgqMpVxF2fSo=,iv:lFhmF5Nn+h+XnXrOPYqUIJxP/ATz2cIcLon4hXThfMk=,tag:UmHMBm/eAXXPodFDBoHFfQ==,type:str]
      stringData:
        GITEA__OAUTH2__JWT_SECRET: ENC[AES256_GCM,data:HWWRpnMfqiNtv8eAb+IylMQ4RgPAsOIKYsL+b++oo35ddrkU8/KYHW+x1w==,iv:a6JhRM9Wx5F/ZDwKzlSD1Hz8bYxql1zQt69FN5l0rcE=,tag:MzIyhkz8JFgMNg0+Lj5Ing==,type:str]
        GITEA__SECURITY__INTERNAL_TOKEN: ENC[AES256_GCM,data:d7I564EfxRN+DCXIYkxNjUu0axtGbIFvohxV4HCL6FZwBW0mFUkAtH6uCyEjtaxcBZHjOnIDaKBTtj+9PnnlLIiyHO5U4xiwBY7bCy7luAYax/OwAURIg5vUYZW0iSAWUu5O5ch0Zgrp,iv:NVBbCypDVA34KCVb8PXP6dHvH1DiwtatW3JrytIdXZY=,tag:D0pe/dCzzf54nJXyos2DJA==,type:str]
        GITEA__SECURITY__SECRET_KEY: ENC[AES256_GCM,data:54wvV4b02L/Goaoo2rp1wvEujaIi4ZSF1qnRwxRUuHizHDrs1v9sFFqb6cJG2Q97ev9mlydLSKV4wN4Ng3lfCw==,iv:bt6+EMM6irrWxZGKbylqOqDhkZ/TyB/k50YFmI7ksdY=,tag:IvcXlS5ZVEbTlPSY2D5rZA==,type:str]
        GITEA__SERVER__LFS_JWT_SECRET: ENC[AES256_GCM,data:y2u0ezlRi9VGEXWdUIzm1X/RppccRrLl+Rdn8f7wjdqp1tYR0F1epvzJNw==,iv:kulprqKD83WyvuJBwXOr8gIRTldd9eh+2Naphdk3Gdk=,tag:OMOiXtzK22AmKx5cJNeMxQ==,type:str]
    - name: ENC[AES256_GCM,data:P7kQH98AB98ayxkzMDHnYQ==,iv:gW1iNBv/OdYkz3PTrtPw6Sj5wcVPi6rZVL7iTV2KFpA=,tag:lPrzMI4AQVid4HxK1vzgLg==,type:str]
      stringData:
        GITEA_ADMIN_PASSWORD: ENC[AES256_GCM,data:TlwCrqguXJF19AKxX6hJpw==,iv:/qci7xYQ0A410TQY/U2xlQvGZ38AqUpHIYEsL7FPeK4=,tag:tGIe38U+bOIxSf5lIclAfQ==,type:str]
        GITEA_ADMIN_USERNAME: ENC[AES256_GCM,data:uBZHl2v2ZClIQqE=,iv:DZxTpuaS7l36Zx++CRvlzRS0PgVWg0zuwIYB9xyMQUY=,tag:UWiem5IajUMyctOa0LNiAw==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdzJuTUZ6Y29jeGlYYVRa
        V1RocVJ2bWtiMWF4NnNMMjJaT05wRGhEdzJjCnltT3g1UFdORWovUW1KSVpCTTd5
        VWZURmNnd2hzRHhoSGZLdDhDeUpNTGsKLS0tIGY4L1RHZVJIdHZoMEd4aklPbnMr
        N1FhZGx3bXFYZEZrVkxCQzVGYTR0bkUKyblkKOfZbiY2WxVkoFTxnNSroy0pVdyj
        MksBLbUlaAXOlBS86IaCX8tsi9qTPQnFdpyLwt6wPHVFeORcvY02xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T06:37:24Z"
  mac: ENC[AES256_GCM,data:zgqOMHh4IwSX1BY8QakzB5UAHsjRM8wD1ANnIEitTpO3315CXrbNfDpWP1kJo1vq3gGsQ+0wa2IwGdC1areu5GiECv9PvUQsZs96+o+0cBCfl+NJpWTNSIDj/bxNBrTMGNEjf/RZ1FhhbvUuj9fRBiQ4n6DMKssQDMCCdQ5vYPI=,iv:J80Yk0ISG0W9UGzoytUq9wyeqcs72IJDztB29tKNES8=,tag:1AD+Hcd7OrTCOjZpEQ8EeQ==,type:str]
  encrypted_suffix: Templates
  version: 3.11.0
