---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slskr-api
  namespace: slskr
spec:
  dnsNames:
    - slskr.example.com
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 8h
  secretName: slskr-api-tls
