apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig
  namespace: slskr
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:HUZ7EoQfXNBHPWDHAKK5JbJhew4n6anYGDRKcrPPAXSjnS/Tc6Ici7NVv5fIPK7WXcTR68QVs5vrZF9TzJMFNN6YpYXIBs70tT0m68BKsYwY0oWin1iOkbXSSbwFCKnBOFzPFw+y93sBFloUChZwuzyk4F6GbZASXg+b+wdYZmgHAFpcDQ6oCGD0ZWIRR0e9PDpudWg=,iv:F6irWTtig2YeHCwZl/adxZUH5XhvKZ0YFcHx9UINvvk=,tag:j8VNxPPdp8rlu74MK4drcw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdjZZS0NBMkFCYnc3L0FF
        TS9oc21GYm4wV3Q1STAvZDVSQjNNSGladzJnClF0b2x1Y3BLdHlpUFV1akRjSjhX
        OWJHaW9URTU5UlZlUzlpbkF0VXRYa3MKLS0tIGxkd0tCMWZtdjg2djlVdlB2SE5H
        eUtlNkZOelJUb01zdXQxUVJJbWN4UlkKoGmr0u7bJ2jlWpR7szhKSg/BtNL01XTY
        +wSyEhqePnge3OB3+gwXHJ17ha647ChBwbpByK54Sya2BEe5LUSZHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T18:15:00Z"
  mac: ENC[AES256_GCM,data:FYDifaFeGcINFXiXP1QBow1CKPDD7p1J14VLPdvSQE/zPAvhEn83fv3oYoKBVla90SoyH8T7Z8yylAYvzPC2Wk/vvjNjc9UsGEwjeGJheiGDpp1TRsUbN7t3GBwDqK39/jIMcQoePvZCpnijtSGS8NpkbCx6zgtBgeBhjc4kTiU=,iv:j0o8iBwmUvFI6vL/2Ja6KroXZ3gEd0iBBVaUW1CbOo4=,tag:bNdagKDcRqK40X5ZUuji+Q==,type:str]
  version: 3.13.3
