---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-data
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/gitea
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
