apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: gitea-docker
  namespace: gitea
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:oC2yZqLnbtu7Lg==,iv:9D5YG4W3bo6OtdTdLczcypRjNUGMmJtEVubYKhS+4/w=,tag:kfL5hLllJbxoZkDKV7JB/A==,type:str]
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:eQEZdQKnuXtopZVtMnNc/EESwU3Diz7AAC2QFOq8iGDRh1ln1vQYjI9IHwyKfHwYma3T92OuTUaxKhOHyLzpth/2rR8sjOFFocoTaEYBF4JuY2NPiWVsBEXy5iHAPVc9ArHmtKaf5PdifCsHKEicOM2N3GXWhmLlmftIAxmt97mQySy4blsdoMgO/WSw1+cWfQQExv0=,iv:fNR3I+8ZG3QipAaIUbWIzLzDLiROAr8kjCg0adWMx24=,tag:EwCyQom1E4rQFYNiMIHfIw==,type:str]
      type: ENC[AES256_GCM,data:CGyUw6Ihj4Oy+Ww81RVLlgpzWbf3As5psB0ean/m,iv:6UenKc9psGTEVIaGITiaIQX1RWJbmTCh17I6g687NHg=,tag:54u33aKqB9IKEBB4+qPfkQ==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR3BOWE5PLytpMS8zLytQ
        QjB6UnFYeWRDMCtFaWZrWEVISkVTcCs5ZUVNCkQwb0xxblIvbDJ2ZGpubnoxdmhD
        NnNiVWRUNmJUaHB0Tk55UUdmMmRsb1EKLS0tIFQ4MnZDSkZReTRrZU1wOWhReGt1
        cy8yNllwTEdZV1RDQUV2THUzMlR3R2MKFQ4sGL+WrwFiYwFv0Gv80nAkffuNnCdp
        d0c25fkMblaZTgOpXcdzM+HD5Q5qTzMWdTuaQI/yuHu1TDWfAnwNNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T23:55:43Z"
  mac: ENC[AES256_GCM,data:AeqV9wQ2wcVA2xMLf7bygpimJoyFceK5LepF1oObAZ/cn4BvNoSceBYzx9kU128kViA7dc/R+6yJUnxxfdFeJo09ah7UrkZQAX60KTMfjBFWfjBrnaYUvkF2sv5cU8xFaUK8H8AP76Im4VmB7Jcoy1W0NMWIgoX0NDCDw2e88QU=,iv:H3JMk1JR+NAR0Hh1GYoLiKGZ9qe5fHV5+N4MEx7jars=,tag:cpMk0ZYVDdNE2DMAPpU4Zw==,type:str]
  encrypted_suffix: Templates
  version: 3.12.1
