---
apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  labels:
    app.kubernetes.io/name: nextcloud
  name: nextcloud-redis
spec:
  certIssuer: selfsigned
  certIssuerType: ClusterIssuer
  exporterImage: ghcr.io/hyperspike/valkey-sidecar:latest
  externalAccess:
    enabled: false
  image: ghcr.io/hyperspike/valkey:v0.0.61
  nodes: 1
  prometheus: false # TODO: true
  # prometheusLabels:
  #   prometheus: prometheus
  replicas: 0
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
  storage:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: local-path
  tls: true
  volumePermissions: true
