---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github-status
  namespace: flux-system
spec:
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
  providerRef:
    name: github
