---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: searxng
  namespace: searxng
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
  podSelector:
    matchLabels:
      app: searxng
  policyTypes:
    - Ingress
