---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1h
  url: https://istio-release.storage.googleapis.com/charts/
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.29.0
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 1h
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.29.0
  install:
    remediation:
      retries: 3
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: replace
                path: /spec/revisionHistoryLimit
                value: 0
              - op: remove
                path: /spec/template/spec/containers/0/resources
            target:
              kind: Deployment
  values:
    autoscaleEnabled: false
    global:
      networkPolicy:
        enabled: true
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.29.0
  install:
    remediation:
      retries: 3
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: remove
                path: /spec/template/spec/containers/0/resources
            target:
              kind: DaemonSet
  values:
    global:
      networkPolicy:
        enabled: true
    istioOwnedCNIConfig: true
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  chart:
    spec:
      chart: ztunnel
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.29.0
  install:
    remediation:
      retries: 3
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: remove
                path: /spec/template/spec/containers/0/resources
            target:
              kind: DaemonSet
  values:
    global:
      networkPolicy:
        enabled: true
    profile: ambient
