---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: flux-system
spec:
  interval: 1h
  url: https://stakater.github.io/stakater-charts/
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: disabled
    pod-security.kubernetes.io/enforce: restricted
  name: reloader
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      version: 2.2.8
  install:
    remediation:
      retries: 3
  interval: 1h
  values:
    reloader:
      deployment:
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        revisionHistoryLimit: 0
      netpol:
        enabled: true
      readOnlyRootFileSystem: true
      reloadOnCreate: true
      reloadOnDelete: true
      syncAfterRestart: true
