---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /srv/immich
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: immich-database
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 10Gi
#   hostPath:
#     path: /srv/immich/database
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   volumeMode: Filesystem
