---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /srv/immich
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
