---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: miniflux
    app.kubernetes.io/name: miniflux-data
  name: miniflux-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: miniflux-data
    namespace: miniflux
  iscsi:
    fsType: btrfs
    iqn: ${ISCSI_IQN}
    lun: 5
    targetPortal: ${ISCSI_TARGET_PORTAL}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
