---
kind: Namespace
apiVersion: v1
metadata:
  annotations: {}
  labels:
    linkerd.io/extension: viz
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: restricted
  name: linkerd-viz
