---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-data
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: lidarr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: media-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-downloads
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: nzbget-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-data
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: ombi-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-data
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: prowlarr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: radarr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: sonarr-data
