---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-data
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/lidarr
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Ti
  hostPath:
    path: /srv/media
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nzbget-downloads
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/nzbget
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ombi-data
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/ombi
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-data
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/prowlarr
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-data
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/radarr
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-data
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/sonarr
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
