---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: claw
    app.kubernetes.io/name: zeptoclaw-data
  name: zeptoclaw-data
  namespace: claw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: zeptoclaw-data
