# yamllint disable rule:line-length
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: sops
spec:
  chart:
    spec:
      chart: sops-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: sops
        namespace: flux-system
      version: 0.25.0
  install:
    crds: Skip
    remediation:
      retries: 3
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: add
                path: /metadata/annotations/secret.reloader.stakater.com~1reload
                value: sops-age-key-file
              - op: add
                path: /spec/template/spec/containers/0/securityContext/allowPrivilegeEscalation
                value: false
              - op: replace
                path: /spec/template/spec/containers/0/securityContext/capabilities/drop
                value:
                  - ALL
            target:
              kind: Deployment
  upgrade:
    crds: Skip
  values:
    extraEnv:
      - name: SOPS_AGE_KEY_FILE
        value: /etc/sops-age-key-file/key
    secretsAsFiles:
      - mountPath: /etc/sops-age-key-file
        name: sops-age-key-file
        secretName: sops-age-key-file
    securityContext:
      container:
        enabled: true
      enabled: true
