---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations: {}
  labels:
    app: ingress
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: istio
    istio.io/dataplane-mode: none
    istio: ingress
  name: ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress
subjects:
  - kind: ServiceAccount
    name: ingress
