---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitea
  # - gitea-actions
  # - homebridge
  - llama-cpp
  - login
  - media-server
  - miniflux
  - mitmproxy
  - redirector
  - rsshub
  - search
  - social
  - slskr
  - vaultwarden
