---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/component: cronjob
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/name: nextcloud
  name: nextcloud-cron
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: cronjob
        app.kubernetes.io/instance: nextcloud
        app.kubernetes.io/name: nextcloud
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/component: cronjob
            app.kubernetes.io/instance: nextcloud
            app.kubernetes.io/name: nextcloud
        spec:
          containers:
            - command:
                - php
                - -f
                - /var/www/html/cron.php
                - --
                - --verbose
              env:
                - name: NEXTCLOUD_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: nextcloud-password
                      name: nextcloud
                - name: NEXTCLOUD_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: nextcloud-username
                      name: nextcloud
                - name: NEXTCLOUD_DATA_DIR
                  value: /var/www/html/data
                - name: POSTGRES_DB
                  value: nextcloud
                - name: POSTGRES_HOST
                  value: nextcloud-postgres
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: postgres-password
                      name: nextcloud-postgres
                - name: POSTGRES_USER
                  value: nextcloud
                - name: REDIS_HOST
                  value: nextcloud-redis
                - name: REDIS_HOST_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: nextcloud-redis
                - name: REDIS_HOST_PORT
                  value: !!str 6379
              image: docker.io/library/nextcloud:32.0.5-apache
              imagePullPolicy: IfNotPresent
              name: nextcloud-cron
              resources: {}
              volumeMounts:
                - mountPath: /var/www/
                  name: nextcloud-main
                  subPath: root
                - mountPath: /var/www/html
                  name: nextcloud-main
                  subPath: html
                - mountPath: /var/www/html/config
                  name: nextcloud-main
                  subPath: config
                - mountPath: /var/www/html/custom_apps
                  name: nextcloud-main
                  subPath: custom_apps
                - mountPath: /var/www/html/data
                  name: nextcloud-main
                  subPath: data
                - mountPath: /var/www/html/themes
                  name: nextcloud-main
                  subPath: themes
                - mountPath: /var/www/tmp
                  name: nextcloud-main
                  subPath: tmp
          restartPolicy: Never
          securityContext:
            # Will mount configuration files as www-data (id: 33) for nextcloud
            fsGroup: 33
          volumes:
            - name: nextcloud-main
              persistentVolumeClaim:
                claimName: nextcloud-data
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
