---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden
spec:
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  renewBefore: 8h
  secretName: vaultwarden-tls
