---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reloader-metadata-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - watch
      - create
      - update
