---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      version: 2.21.0
  install:
    remediation:
      retries: 3
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: replace
                path: /spec/revisionHistoryLimit
                value: 0
              - op: remove
                path: /spec/template/spec/containers/0/resources
            target:
              kind: Deployment
  values:
    auth:
      strategy: anonymous
    deployment:
      view_only_mode: true
    external_services:
      custom_dashboards:
        enabled: false
      grafana:
        enabled: false
      istio:
        gateway_api_classes:
          - class_name: traefik
            name: Traefik
    server:
      observability:
        metrics:
          enabled: false
